### ISSUE TITLE
Small icons on mobile

### ISSUE THREAD

**Issue by shutosheep** [AleDenshi/comfy.guide#17]
Not sure why but the icons on the front page is extremely small on mobile.

![1708663387637416536](https://github.com/AleDenshi/comfy.guide/assets/103938611/94b9a461-d000-48c2-b914-73b5248152a5)

I assume the size of these svgs are controlled by this css rule

```css
.pages img {
        max-height: 2em;
}
```

I suggest specifying the max width and height with the `rem` values, since it would result in much better looking.
However some svgs that are vertically or horizontally long will look squished with this. (Hugo icon is good example)

```css
.pages img {
        max-width: 2rem;
        max-height: 2rem;
}
```

![1708664481286925868](https://github.com/AleDenshi/comfy.guide/assets/103938611/c440df05-241f-4ba2-8bdf-1c9aa3f27767)
